name: nano_var

description: >-
  A variable that can be subscribed to so the subscribers get notified when
  changes occur.

version: 1.0.1

repository: https://github.com/oborgen/nano_var

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
  nano_mock: ^1.0.2
