name: flutter_nano_var

description: >-
  A lightweight state management library independent from any dependency
  injection methods.

version: 1.0.0

repository: https://github.com/oborgen/nano_var

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  nano_var: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  uuid: ^3.0.1
