name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Install Flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.2'

      # Disable Flutter analytics.
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # Install melos to operate on multiple packages.
      - name: Intall Melos
        run: dart pub global activate melos

      # Add ~/.pub-cache/bin to path to make melos work.
      - name: Pub cache path
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      # Install dependencies by calling "melos bootstrap".
      - name: Install dependencies
        run: melos bootstrap

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: melos exec "dart analyze"

      # Call flutter test and collect coverage.
      - name: Run tests
        run: melos exec "flutter test --coverage"

      # Publish coverage information to codecov.io.
      - name: Publish coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
